---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  cassandra-1:
    image: "cassandra:4.1"
    container_name: "cassandra-1"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"

  cassandra-2:
    image: "cassandra:4.1"
    container_name: "cassandra-2"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-1"

  cassandra-3:
    image: "cassandra:4.1"
    container_name: "cassandra-3"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
    depends_on:
      - "cassandra-2"

  presto-coordinator:
    image: ahanaio/prestodb-sandbox
    ports:
      - "8000:8080"
    container_name: "presto-coordinator"
    volumes:
      - ./presto-config/coordinator-config/config.properties:/opt/presto-server/etc/config.properties
      - ./local_postgres.properties:/opt/presto-server/etc/catalog/local_postgres.properties

  presto-worker-1:
    image: ahanaio/prestodb-sandbox
    container_name: "presto-worker-1"
    volumes:
      - ./presto-config/worker-config/config.properties:/opt/presto-server/etc/config.properties
    depends_on:
      - presto-coordinator

  presto-worker-2:
    image: ahanaio/prestodb-sandbox
    container_name: "presto-worker-2"
    volumes:
      - ./presto-config/worker-config/config.properties:/opt/presto-server/etc/config.properties
    depends_on:
      - presto-coordinator

#  spark-master:
#    image: andreper/spark-master:3.0.0
#    container_name: spark-master
#    ports:
#      - "8080:8080"
#      - "7077:7077"
#    volumes:
#      - shared-workspace:/opt/workspace
#
#  spark-worker-1:
#    image: andreper/spark-worker:3.0.0
#    container_name: spark-worker-1
#    environment:
#      - SPARK_WORKER_CORES=1
#      - SPARK_WORKER_MEMORY=512m
#    ports:
#      - "8081:8081"
#    volumes:
#      - shared-workspace:/opt/workspace
#    depends_on:
#      - spark-master
#
#  spark-worker-2:
#    image: andreper/spark-worker:3.0.0
#    container_name: spark-worker-2
#    environment:
#      - SPARK_WORKER_CORES=1
#      - SPARK_WORKER_MEMORY=512m
#    ports:
#      - "8082:8081"
#    volumes:
#      - shared-workspace:/opt/workspace
#    depends_on:
#      - spark-master

volumes:
  shared-workspace:
    driver: local